version: "3"
services:
  telegram-bot:
    build: .
    image: telegram-bot:1.10
    env_file: .env
    ports:
      - 4000:4000

  swagger:
    image: swaggerapi/swagger-ui:v3.50.0
    environment:
      SWAGGER_JSON: /etc/telegram-bot/swagger.json
    ports:
      - 9090:8080
    volumes:
      - ./docs:/etc/telegram-bot
