@startuml
skinparam componentStyle uml2

cloud {
  () "Telegram Bot API" as TelegramBotAPI
}

package "Main Thread" {
  [Web Server] -up- API
  [Web Server] .down.> [Bot] : sendMessage
  [Web Server] .down.> [Bot] : sendPhoto

  [Bot] .down.> TelegramBotAPI : getUpdates
  [Bot] .down.> TelegramBotAPI : sendMessage
  [Bot] .down.> TelegramBotAPI : sendPhoto
  [Bot] .down.> TelegramBotAPI : editMessageReplyMarkup
}

package "Bot Polling Thread" {
  database "SQLite" {
    [Votes]
  }

  [Bot Polling Loop] .up.> [Votes] : add a vote
  [Bot Polling Loop] .up.> [Votes] : count votes

  [Bot Polling Loop] .down.> [Bot] : getUpdates
  [Bot Polling Loop] .down.> [Bot] : editMessageReplyMarkup
}

[Sending Utility] .down.> API : message
[Sending Utility] .down.> API : photo

@enduml
